### ISSUE TITLE
Credentials in request-body as fallback per 2.3.1 of RFC

### ISSUE THREAD

**Issue by cristiangraz** [ory-am/fosite#22]
Section 2.3.1 of the RFC says:

> Including the client credentials in the request-body using the two
parameters is NOT RECOMMENDED and SHOULD be limited to clients unable
to directly utilize the HTTP Basic authentication scheme (or other
password-based HTTP authentication schemes).  The parameters can only
be transmitted in the request-body and MUST NOT be included in the
request URI.

When using a REST client for mac that support oauth, I realized it was sending ```client_id``` and ```client_secret``` in the request body rather than via the ```Authorization``` header. While it's definitely not recommended for clients to use, does it make sense to have this included as part of the library as a fallback to support that section of the RFC? I'm not sure what the limitation is of sending an Authorization header, but wanted to discuss here before submitting a PR.

If it's something you think would be useful to have as a fallback I have a PR ready to submit with all the tests.

**Comment by arekkas** [comment]
I think that it is easier to filter out the Authorization http header in logs instead of filtering specific values in bodies like `client_id` or `client_secret`. Otherwise I do not know why this method is not recommended.

I realize that some libraries implement faulty behaviour which is why I wrote this library here. I'd rather not include a fallback as I'm trying to follow all the good practices the IETF recommends.

Let me know if you disagree, I'm open for discussion! :)

**Comment by cristiangraz** [comment]
I was actually thinking the same thing -- and not really sure why a client wouldn't be able to send an Authorization header. More of an inconvenience with the rest client I'm using, but I agree this library is stricter than most (which is what I like about it!) and should avoid everything but best practices. Thanks for chiming in so quickly!

**Comment by arekkas** [comment]
Sure, thanks for your thoughts, feedback and contributions! I appreciate it!
